name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone code repo
      uses: actions/checkout@v2
    - name: Build and run unit tests with Buildpack CI
      uses: buildpack-ci/run-tests@v1
