name: build and create container on master

on:
  push: #on: [push, pull_request]
    # Sequence of patterns matched against refs/heads
    branches-ignore:    
      - 'feature/**'
jobs:
  build:
    name: Pack and publish
    runs-on: ubuntu-latest
    steps:
    - name: Clone code repo
      uses: actions/checkout@v2
    - name: Setup Buildpack CI
      uses: buildpacks/github-actions/setup-pack@v5.0.0
    - name: Login Docker Hub  
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    - id: package
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        # echo "GITHUB_SHA::6: ${GITHUB_SHA::6}"
        # echo "GITHUB_SHA: $GITHUB_SHA"
        pack build ${REPO}/demonodejs:${GITHUB_SHA::6} --tag ${REPO}/demonodejs:latest --buildpack paketo-buildpacks/nodejs --builder paketobuildpacks/builder:base --publish
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
  
