name: CI
on: [push, pull_request]
jobs:
  build:
    name: Package, Publish, and Register
    runs-on: ubuntu-latest
    steps:
    - name: Clone code repo
      uses: actions/checkout@v2
    - name: Setup Buildpack CI
      uses: buildpacks/github-actions/setup-pack@v5.0.0
    - name: Login Docker Hub  
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    - id: package
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "GITHUB_SHA: {GITHUB_SHA::6}"
        pack build ${REPO}/demonodejs:latest --buildpack paketo-buildpacks/nodejs --builder paketobuildpacks/builder:base --publish
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
  
