name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone code repo
      uses: actions/checkout@v2
    - name: Setup Buildpack CI
      uses: buildpacks/github-actions/setup-pack@v5.0.0
