name: Release
on: [push, pull_request]
# on:
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        run: |
          #!/usr/bin/env bash
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        env:
          REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
