name: On Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release tag version $GITHUB_REF_NAME
    runs-on: ubuntu-latest
    steps:
    - name: Clone code repo
      uses: actions/checkout@v2
    - name: Setup Buildpack CI
      uses: buildpacks/github-actions/setup-pack@v5.0.0
    - name: Login Docker Hub  
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
    - id: package
      run: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "GITHUB_SHA::6: ${GITHUB_SHA::6}"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME" 
        pack build ${REPO}/demonodejs:$GITHUB_REF_NAME --buildpack paketo-buildpacks/nodejs --builder paketobuildpacks/builder:base --publish
      env:
        REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
