name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        run: |
          #!/usr/bin/env bash
          echo "Hello!"
        env:
          REPO: docker.io/${{ secrets.DOCKER_HUB_USER }}
